[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools >= 44', 'wheel']

[tool.black]
line-length = 79
target-version = ['py37']
exclude = './test_files'

[tool.zimports]
black-line-length = 79
keep-unused-type-checking = true
