name: Release to pypi
# from https://github.com/sqlalchemy/sqlalchemy2-stubs

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          Version to publish.
          Leave default to publish the current version.
          To change version pass the number or a segment like path, minor, major, etc. See https://hatch.pypa.io/1.12/version/#supported-segments for all available segments.
        required: true
        default: '~~version~~'


# env:
  # comment TWINE_REPOSITORY_URL to use the real pypi. NOTE: change also the secret used in TWINE_PASSWORD
  # TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:
  release:
    name: Release
    if: github.actor == 'CaselIT' || github.actor == 'zzzeek'
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install hatch twine
          pip list

      - name: Set version
        # A specific version was set in the action trigger.
        # Change the version in pyproject.toml to that version
        if: ${{ github.event.inputs.version != '~~version~~' }}
        run: |
          hatch version ${{ github.event.inputs.version }}

      - name: Commit version change
        # If the pyproject.toml version was changed, commit it.
        if: ${{ github.event.inputs.version != '~~version~~' }}
        uses: sqlalchemyorg/git-auto-commit-action@sa
        with:
          commit_message: Version ${{ github.event.inputs.version }}
          file_pattern: zimports/__init__.py

      - name: Get version
        # Get current version
        id: get-version
        run: |
          version=`hatch version`
          echo $version
          echo "::set-output name=version::$version"

      - name: Create distribution
        # Create wheel and sdist
        run: |
          python -m hatch build

      - name: Create release
        # Create github tag and release and upload the distribution wheels and sdist
        uses: sqlalchemyorg/action-gh-release@sa
        with:
          body: Release ${{ steps.get-version.outputs.version }}
          files: dist/*
          name: 'v${{ steps.get-version.outputs.version }}'
          tag_name: v${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Next version
        # Update the version to the next version
        run: |
          hatch version patch

      - name: Get version
        # Get new current version
        id: get-new-version
        run: |
          version=`hatch version`
          echo $version
          echo "::set-output name=version::$version"

      - name: Commit next version update
        # Commit new current version
        uses: sqlalchemyorg/git-auto-commit-action@sa
        with:
          commit_message: Start work on ${{ steps.get-new-version.outputs.version }}
          file_pattern: zimports/__init__.py

      - name: Publish distribution
        # Publish to pypi
        env:
          TWINE_USERNAME: __token__
          # replace TWINE_PASSWORD with token for real pypi
          # TWINE_PASSWORD: ${{ secrets.test_pypi_token }}
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: |
          twine upload --skip-existing dist/*
